logo.src = "informatik_ai.png"
logo.href = "https://oeh.jku.at/cs/"

en.title = "English only FAQ"

en.intro = '''
This is an example of a FAQ that is not available in German.
'''

[[questions]]

en.q = "But why?"
en.a = '''
There are some topics where it is simply unnecessary effort to also provide the FAQ in German.
'''
